package dirs

const (
	PROGRAM_FILES     = "C:/Program Files"
	PROGRAM_FILES_X86 = "C:/Program Files (x86)"
	PROGRAM_DATA      = "C:/ProgramData"
	APP_DATA          = "~/AppData"
	APP_DATA_ROAMING  = "~/AppData/Roaming"
	LOCAL_APP_DATA    = "~/AppData/Local"
	TEMP              = "~/AppData/Local/Temp"
	TEMP_SYSTEM       = "C:/Windows/Temp"
	WINDOWS           = "C:/Windows"
	SYSTEM            = "C:/Windows/System32"
	SYSTEM_X86        = "C:/Windows/SysWOW64"
	DESKTOP_USER      = "~/Desktop"
	DESKTOP_SYSTEM    = "C:/Users/Public/Desktop"
	START_MENU_USER   = "~/AppData/Roaming/Microsoft/Windows/Start Menu/Programs"
	START_MENU_SYSTEM = "C:/ProgramData/Microsoft/Windows/Start Menu/Programs"
	DOCUMENTS_USER    = "~/Documents"
	DOCUMENTS_SYSTEM  = "C:/Users/Public/Documents"
	DOWNLOADS_USER    = "~/Downloads"
	DOWNLOADS_SYSTEM  = "C:/Users/Public/Downloads"
	MUSIC_USER        = "~/Music"
	MUSIC_SYSTEM      = "C:/Users/Public/Music"
	PICTURES_USER     = "~/Pictures"
	PICTURES_SYSTEM   = "C:/Users/Public/Pictures"
	VIDEOS_USER       = "~/Videos"
	VIDEOS_SYSTEM     = "C:/Users/Public/Videos"
	FONTS             = "C:/Windows/Fonts"
	TEMPLATES_USER    = "~/AppData/Roaming/Microsoft/Windows/Templates"
	TEMPLATES_SYSTEM  = "C:/Users/Public/Templates"
)
